flowchart TD
    A["Set floor to first floor in queued floors"]
    B["Is there another floor in<br> queued floors not yet gone<br> through?"]
    L["Select next floor from<br> queued floors"]
    C["Is the floor selected from<br> queued floors greater than<br> the current floor?"]
    D["Set checkup to true"]
    E["Is the floor selected from<br> queued floors less than the<br> current floor?"]
    F["Set checkdown to true"]
    G["Is checkup false and<br> checkdown false?"]
    H["Return stop"]
    I["Is checkdown false?"]
    J["Return down"]
    K["Return up"]
    M["Is checkup false?"]
    N["Is the furtherst floor up<br> shorter than the furthest<br> floor down?"]
    A --> B
    B -->|yes| L
    L --> C
    C -->|yes| D
    C -->|no| E
    E -->|yes| F
    D --> G
    E -->|no| G
    F --> G
    G -->|yes| H
    G -->|no| I
    I -->|yes| K
    I -->|no| M
    M -->|yes| J
    M -->|no| N
    N -->|yes| K
    N -->|no| J
