flowchart TD
    A["Set checkup and checkdown to true"]
    B["Are there any calls up?"]
    C["Set checkdown to true"]
    D["Are there any calls down?"]
    E["Set checkup to true"]
    F["Is checkup and checkdown false"]
    G["Return stop"]
    H["Is checkup false"]
    