flowchart TD
    A["Set checkup and checkdown to true"]
    B["Are there any calls up?"]
    C["Set checkdown to true"]
    D["Are there any calls down?"]
    E["Set checkup to true"]
    F["Is checkup and checkdown false"]
    G["Return stop"]
    H["Is checkup false?"]
    I["Return down"]
    IA["Is checkdown false?"]
    IB["Return up"]
    J["Set final up to the minimum of the calls up"]
    K["Set final down to the minimum of the calls down"]
    L["Is the difference between the current floor and the longest down call greater than the difference between the current floor and the longest call up?"]
    M["Return down"]
    N["Return up"]
    A --> B
    B -->|yes| C
    B -->|no| D
    C --> D
    D -->|yes| E
    D -->|no| F
    E --> F
    F -->|yes| G
    F -->|no| H
    H -->|yes| I
    H -->|no| IA
    IA -->|yes| IB
    IA -->|no| J
    J --> K
    K --> L
    L -->|yes| M
    L -->|no| N